# Melon Chart top 100수집 [타이틀|아티스트]

- 타이틀과, 아티스트 명을 beautifulsoup 사용해서 수집
- for loop 적용
- 마지막으로, 데이터를 Pandas Library의 Dataframe에 집어넣기
- 데이터 저장 파일을 내보내기

In [1]:
# 라이브러리 로딩
import requests as req
from bs4 import BeautifulSoup as bs

import pandas as pd

In [2]:
url = 'https://www.melon.com/chart/'
req.get(url)
    # 406 클라이언트의 요청이 문제
    
    # 브라우저 대 브라우저가 아닌, 코드로 인식을 해서 접근을 멜론에서 막음

In [3]:
head = {'User-Agent' : 'https://www.melon.com/chart/'}

In [4]:
res_melon = req.get('https://www.melon.com/chart/', headers = head)
res_melon

# BeautifulSoup 객체화

In [7]:
soup = bs(res_melon.text,'lxml')
soup

<!DOCTYPE html>
<html lang="ko">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<title>멜론차트&gt;TOP100&gt;멜론</title>
<meta content="음악서비스, 멜론차트, 멜론TOP100, 최신음악, 인기가요, 뮤직비디오, 앨범, 플레이어, 스트리밍, 다운로드, 아티스트플러스, 아티스트채널" name="keywords"/>
<meta content="No.1 뮤직플랫폼 멜론! 최신 트렌드부터 나를 아는 똑똑한 음악추천까지!" name="description"/>
<meta content="ee85ff6db1fa8f2226bcb671ecb2bcdbcffb6f8b" name="naver-site-verification"/>
<meta content="q4tbTQhmxa4La3OdNLsNOCxrJ_WV6lUlBFrFW4-HqQc" name="google-site-verification"/>
<meta content="357952407588971" property="fb:app_id"/>
<meta content="Melon" property="og:title"/>
<meta content="https://cdnimg.melon.co.kr/resource/image/web/common/logo_melon142x99.png" property="og:image"/>
<meta content="음악이 필요한 순간, 멜론" property="og:description"/>
<meta content="http://www.melon.com/chart/" property="og:url"/>
<meta content="website" property="og:type"/>
<meta content="멜론" property="og:site_name"/>
<meta content="width=device-width" name="viewport"/>
<link href="/favicon.ico?2" id="favicon" rel="shortcut icon" type="image/x-icon"/>
<link href="https://cdnimg.melon.co.kr/static/web/resource/style/w1/av/i/qrguc73w.css" rel="stylesheet" type="text/css"/>
<link href="https://cdnimg.melon.co.kr/static/web/resource/style/w1/ri/4/rw98ltzfrqdnf.css" rel="stylesheet" type="text/css"/>
<!-- 댓글 css 파일 네임 변경 -->
<link href="https://cdnimg.melon.co.kr/static/web/resource/style/w1/dn/4/ynesuqe51i.css" rel="stylesheet" type="text/css"/>
<link href="https://cdnimg.melon.co.kr/static/web/resource/style/w1/0h/a/bhkepxh8.css" rel="stylesheet" type="text/css"/>
<link href="/resource/style/web/chart/melonweb_chart_4x.css" rel="stylesheet" type="text/css"/>
<link href="https://cdnimg.melon.co.kr/static/web/resource/style/w1/0h/a/bhkepxh8.css" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Nunito:400" rel="stylesheet"/>
<script src="/resource/script/cds/common/web/member_api.js" type="text/javascript"></script>
<script src="/resource/script/cds/common/web/commerce_api.js" type="text/javascript"></script>
<script src="/resource/script/web/common/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="https://member.melon.com/resource/script/web/member/melonweb_member_external.js?tm=20230501" type="text/javascript"></script>
<script src="https://cdnimg.melon.co.kr/static/web/resource/script/w1/c1/d/7j9pwitvgh7.js" type="text/javascript"></script>
<script type="text/javascript">
	(function() {
		WEBPOCIMG = {
			defaultImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				var thumbType = "_500";
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultAlbumImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},

			defaultArtistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultDjImg : function(obj){
			},
			defaultMvImg : function(obj, width, height){
				if(width == null || width == '') width = $(obj).width();
				if(height == null || height == '') height = $(obj).height();

				var ratio43 = Math.floor((4/3)*10)/10;
				var ratio169 = Math.floor((16/9)*10)/10;
				var ratioObj = Math.floor((width/height)*10)/10;

				var ratio = "4x3";
				if(ratioObj == ratio43){
					ratio = "4x3"; //contentsType = "mv43";
				} else if(ratioObj == ratio169){
					ratio = "16x9"; //contentsType = "mv169";
				} else {
					if(ratioObj > 1.5) ratio = "16x9";
					else ratio = "4x3";
				}

				if(width == 0) width = 640;
				if(height == 0) ratio = "16x9";

				//가장 큰사이즈로 리사이즈함
				var thumbType = "_" + ratio + "_640";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noMovie" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPlaylistImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultMemberImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 300;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_300";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noArtist" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultPhotoImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 500;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_500";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShopImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				if(width == 0) width = 256;
				//가장 큰사이즈로 리사이즈함
				var thumbType = "_256";
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noProduct" + thumbType + "_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultShowwingImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noShowing" + thumbType + ".jpg";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultTicketImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();

				var thumbType = "_256";
				if(width > 0 && width <= 300){
					thumbType = "_256";
				} else {
					thumbType = "_313";//추후 조절값
				}
				var altSrc = "//cdnimg.melon.co.kr/resource/image/web/default/noTicket" + thumbType + ".png";
				if(obj.src != altSrc){
					obj.src = altSrc;
				}
			},
			defaultSmartRadioImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noSmartradio_59_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			},
			defaultConcertImg : function(obj, width){
				if(width == null || width == '') width = $(obj).width();
				var defaultImg = "//cdnimg.melon.co.kr/resource/image/web/default/noAlbum_114_160727.jpg/melon/resize/" + width;
				if(obj.src != defaultImg){
					obj.src = defaultImg;
				}
			}
		}
		,WEBELLIPSIS = {
			ellipsis : function(ellipsisName,moreClassName,eWidth){
		        //아티스트 더보기
		        var arObj = $('.' + ellipsisName);
		        for(var i = 0; i < arObj.length; i++){
		            if (arObj.eq(i).width() > eWidth ){
		                arObj.eq(i).parent().parent().parent().find('.' + moreClassName).show();
		            }
		        }
			}
		}
	})();
	</script>
</head>
<body>
<div id="wrap">
<div id="skip_nav">skip navigation
		<ul>
<li><a href="#gnb_menu">메뉴</a></li>
<li><a href="#conts_section">본문</a></li>
<li><a href="#footer">하단 정보</a></li>
</ul>
</div>
<!--  header -->
<div class="gnb2_expn" id="header">
<div class="my_fold" id="header_wrap"> <!-- 1024이상 마이영역 접었을때 클래스 my_fold 추가 -->
<div class="clfix" id="gnb">
<!-- 상단 빠른 메뉴 -->
<div id="util_menu">
<p class="none">상단 빠른 메뉴</p>
<div class="top_left">
<ul class="clfix">
<li class="first_child d_melon_ticket"><a class="menu01 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V08&amp;ACTION_AF_CLICK=V1" href="https://ticket.melon.com/main/index.htm" title="멜론 티켓"><span>멜론 티켓</span></a></li>
</ul>
</div>
<!-- 140603_수정 -->
<div class="top_right">
<ul class="clfix">
<li class="first_child"><a class="menu01 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B01&amp;ACTION_AF_CLICK=V1" href="/commerce/pamphlet/web/sale_listMainView.htm" title="이용권구매"><span>이용권구매</span></a></li>
<li><a class="menu02 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V06&amp;ACTION_AF_CLICK=V1" href="/event/vip/index.htm" title="멜론라운지"><span>멜론라운지</span></a></li>
<li><a class="menu03 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=B03&amp;ACTION_AF_CLICK=V1" href="/event/index.htm" title="이벤트"><span>이벤트</span></a></li>
<li class="last_child"><a class="menu04 mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=V02&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/customer/announce/index.htm" title="공지사항"><span>공지사항</span></a></li>
</ul>
<script type="text/javascript">
							var html = '';
							var logoutReturnUrl = window.location.href;

							if(logoutReturnUrl == ''){
								logoutReturnUrl = 'www.melon.com';
							}

							if(isMelonLogin()){

								var memberKey = getMemberKey()
								var memberInfo = svcMember.displayIdByMemberKey(memberKey);
								var memberType = svcMember.getMemberType().MEMBERTYPE;
								var gradeInfo = svcMember.gradeInfoByMemberKey(memberKey);

								var memId = '';
								if(memberType == undefined || memberType == null){
									memberType = '0';
								}

								if(memberInfo.DISPLAYID != undefined || memberInfo.DISPLAYID != null){
									memId = memberInfo.DISPLAYID;
								}

								if(memId.indexOf("@") != -1 && memberType != '1'){//카카오계정이 아닌경우에만 @도메인 영역 삭제처리
									memId = memId.split("@")[0];
								}

								var fromMPS = getCookie("MPS"); // 멜론 플레이어에서 왔는지 확인.
								var fromMPSYn = fromMPS == null || fromMPS.indexOf("MELONPLAYER") < 0;

								var gradeImg = "";
								var gradeName = gradeInfo.GRADE;
								var gradeImageUrl = gradeInfo.HTTPSIMAGEURL;

								if(gradeName == undefined || gradeName == null){
									gradeName = '일반';
								}

								try {

									gradeImageUrl = gradeImageUrl.replace('http:','');

									if(gradeName == '일반'){
										gradeImageUrl = "";
									}

									if(gradeImageUrl != ''){
										gradeImg = "<span class=\"icon_logon\"><img src=\""+gradeImageUrl+"\" width=\"18\" height=\"18\" alt=\""+gradeName+"\" /></span>";
									}
									//카카오연동확인
									if(memberType == '1'){
										gradeImg += '<span class="icon_logon"><img src="//cdnimg.melon.co.kr/resource/image/web/common/icon_kakao.png" width="18" height="18" alt="kakao"></span>';
									}
								} catch (e) {}

								var logoutButtonHtml = '<button type="button" title="로그아웃" class="btn_top_logout" onclick="javascript:MELON.WEBSVC.POC.logout(\'\');"><img src="//cdnimg.melon.co.kr/resource/image/web/common/btn_top_logout.png" width="44" height="12" alt="로그아웃"></button>';

								html = ['<div class="header_login">',
									' <span class="icon_grade">',
									'' + gradeImg + '',
									' </span>',
									' <span class="wrap_id"><a href="javascript:location.href=_getHttpsMemberDomain()+ \'/muid/web/help/myinfointro_inform.htm\';" class="user_id"><strong>' + memId + '</strong></a> 님</span>',
									fromMPSYn ? logoutButtonHtml : '', //멜론 플레이어에서 로그아웃 싱크 안맞는 이슈로 인해 로그아웃 멜론 플레이어에서 왔을 시 버튼 제거
									'</div>'
								].join('');
								document.write(html);
							}
						</script>
</div>
<!-- //140603_수정 -->
</div>
<!-- //상단 빠른 메뉴 -->
<!-- 140603_수정 -->
<h1><a class="mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=M01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/index.htm" title="MelOn 로고 - 홈으로 이동"><img alt="Melon" height="99" src="https://cdnimg.melon.co.kr/resource/image/web/common/logo_melon142x99.png" width="142"/></a></h1>
<!-- //140603_수정 -->
<!-- 통합검색 영역 -->
<fieldset>
<legend>통합검색영역</legend>
<input id="top_search" name="" onkeypress="if(event.keyCode == 13){goSearch();}" placeholder="" style="width:249px" title="검색 입력 편집창" type="text"/><input id="keywordLink" name="keywordLink" type="hidden" value=""/>
<button class="btn_icon btn_auto close" id="top_search_autocomplete_toggle" style="display: none;" title="자동검색 펼침" type="button"><span class="odd_span">자동검색 펼침</span></button> <!-- open/close 클래스 사용 -->
<button class="btn_icon search_m" title="검색" type="button"><span class="odd_span">검색</span></button>
<div class="auto_complete" id="top_search_autocomplete"><div class="auto_complete_cont" style="display:block;"><!-- 자동완성 레이어 --></div></div>
<div class="auto_complete" id="top_search_autocomplete_template" style="display: none;"> <!-- 자동완성 레이어 템플릿 -->
<!-- 텍스트 결과 -->
<ul class="text_result">
<li><a class="autocomplete-label" href="#"></a></li>
</ul>
<!-- 섬네일 결과 -->
<ul class="thumb_result">
<li class="cate"></li>
<li class="class02">
<a href="#">
<span class="thumb_40">
<span class="thumb_frame"></span>
<img alt="" class="autocomplete-img" height="40" width="40"/>
</span>
<div class="info">
<span class="autocomplete-label"></span><br/>
<span><span class="f11 autocomplete-info"></span></span>
</div>
</a>
</li>
</ul>
<!-- 검색어가 없을 때 -->
<ul class="text_result">
<li class="result_none">
<span>해당글자로 시작하는 단어가 없습니다.</span>
</li>
</ul>
</div>
</fieldset>
<form action="" id="searchFrm" method="get" style="display: none">
<input name="q" type="hidden"/>
<input name="section" type="hidden"/>
</form>
<!-- //통합검색 영역 -->
<!-- 실시간 검색어 -->
<div class="realtime_soar_keyword">
<!-- 140519_수정 -->
<a class="title" href="#none">급상승 키워드</a>
<!-- //140519_수정 -->
<div class="keyword_overlay">
<ol style="overflow:hidden; height:20px;">
</ol>
<!-- 140423_추가 -->
<!-- //140423_추가 -->
</div>
</div>
<!-- //실시간 검색어 -->
<!-- 배너 영역 -->
<div class="cmn_banner"></div>
</div>
<!-- 140314_gnb마크업 수정 -->
<div id="gnb_menu">
<ul>
<li class="nth1 on">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=R01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/chart/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu01">멜론차트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child on"><a href="//www.melon.com/chart/index.htm"><span class="menu_chart m1">TOP100</span></a></li>
<li class=""><a href="//www.melon.com/chart/day/index.htm"><span class="menu_chart m2">일간</span></a></li>
<li class=""><a href="//www.melon.com/chart/week/index.htm"><span class="menu_chart m3">주간</span></a></li>
<li class=""><a href="//www.melon.com/chart/month/index.htm"><span class="menu_chart m4">월간</span></a></li>
<li class=""><a href="//www.melon.com/chart/age/index.htm"><span class="menu_chart m5">시대</span></a></li>
</ul>
<div class="chart_finder">
<button class="btn_chart_f" onclick="location.href='//www.melon.com/chart/search/index.htm'" type="button"><span class="odd_span">차트 파인더</span></button>
</div>
</div>
</li>
<li class="nth2">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C01&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/new/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu02">최신 음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/new/index.htm"><span class="menu_new m1">최신곡</span></a></li>
<li class=""><a href="//www.melon.com/new/album/index.htm"><span class="menu_new m2">최신앨범</span></a></li>
<li class=""><a href="//www.melon.com/new/mv/index.htm"><span class="menu_new m3">최신 뮤직비디오</span></a></li>
</ul>
</div>
</li>
<li class="nth3">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=C03&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu03">장르 음악</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0100"><span class="menu_gnr nm1">한국대중음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN0900"><span class="menu_gnr nm2">해외POP음악</span></a></li>
<li class=""><a href="//www.melon.com/genre/song_list.htm?gnrCode=GN1500"><span class="menu_gnr nm3">그외 인기장르</span></a></li>
</ul>
</div>
</li>
<li class="nth4">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S04&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/dj/today/djtoday_list.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu04">멜론DJ</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/dj/today/djtoday_list.htm"><span class="menu_dj m1">오늘은 뭘 듣지</span></a></li>
<li class=""><a href="//www.melon.com/dj/essential/djessential_list.htm"><span class="menu_dj m2">전문가 선곡</span></a></li>
<li class=""><a href="//www.melon.com/dj/themegenre/djthemegenre_list.htm"><span class="menu_dj m3">#테마장르</span></a></li>
<li class=""><a href="//www.melon.com/dj/powerdj/djpowerdj_list.htm"><span class="menu_dj m4">파워DJ</span></a></li>
<li class=""><a href="//www.melon.com/dj/chart/djchart_list.htm"><span class="menu_dj m5">인기</span></a></li>
</ul>
</div>
</li>
<li class="nth5">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S05&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/tv/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu05">멜론TV</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/tv/index.htm"><span class="menu_tv m1">오늘은 뭘 볼까</span></a></li>
<li class=""><a href="//www.melon.com/tv/mv/index.htm"><span class="menu_tv m2">뮤직비디오</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=1"><span class="menu_tv m3">멜론 오리지널</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=4"><span class="menu_tv m4">아티스트 업데이트</span></a></li>
<li class=""><a href="//www.melon.com/tv/menu/index.htm?menuSeq=3"><span class="menu_tv m5">방송</span></a></li>
</ul>
</div>
</li>
<li class="nth6">
<a class="cur_menu mlog" data="LOG_PRT_CODE=1&amp;MENU_PRT_CODE=0&amp;MENU_ID_LV1=&amp;CLICK_AREA_PRT_CODE=S07&amp;ACTION_AF_CLICK=V1" href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="cur_status none">현재 선택된 메뉴-</span><span class="menu_bg menu06">스타포스트</span></a>
<div class="lay_menu">
<ul>
<li class="first_child"><a href="//www.melon.com/artistplus/todayupdate/index.htm"><span class="menu_arti m1">NOW</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/artistchart/index.htm"><span class="menu_arti m3">아티스트 랭킹</span></a></li>
<li class=""><a href="//www.melon.com/artistplus/myranking/index.htm"><span class="menu_arti m4">마이 랭킹</span></a></li>
</ul>
<div class="menu_artist_btn">
<div class="artist_fan">
<button class="btn_fan" onclick="MELON.WEBSVC.POC.menu.goMyMusicFanSignArtist();" type="button"><span class="odd_span">팬맺은 아티스트</span></button>
</div>
<div class="artist_finder">

# CSS Selector

- tag selector('tag 이름') (google tab 실습 때 사용함)
- id selector (#)
- class selector(.)(네이버 메일, 메뉴 실습 때 사용함)
- child selector (>)

In [13]:
# selector로 요소'들'을 뽑아보자
titles = soup.select('div.ellipsis.rank01 > span > a')
titles[0].text

'I AM'

In [14]:
# for loop
for i in range(len(titles)):
    print(titles[i].text)

I AM
Kitsch
꽃
손오공
파이팅 해야지 (Feat. 이영지)
Ditto
Hype boy
사람 Pt.2 (feat. 아이유)
OMG
사랑은 늘 도망가
F*ck My Life
Teddy Bear
FRIEND THE END
사건의 지평선
우리들의 블루스
I Don't Think That I Like Her
CHRISTIAN
다시 만날 수 있을까
London Boy
After LIKE
Polaroid
심(心)
이제 나만 믿어요
Like Crazy
먼지
무지개
빛이 나는 너에게
아버지
물론
Love Me Like This
Attention
ANTIFRAGILE
A bientot
LOVE DIVE
April shower
인생찬가
헤어지자 말해요
Cupid
사랑하지 않아서 그랬어
손이 참 곱던 그대
Fire
사랑해 진짜
I Don't Understand But I Luv U
NIGHT DANCER
연애편지
Dangerously
보금자리
사랑인가 봐
Dynamite
Heaven(2023)
사랑하기 싫어
Zero
밤이 무서워요 (Lonely Night)
Nostalgia
봄날
HOT
너의 모든 순간
Perfume
Candy
가질 수 없는 너
건물 사이에 피어난 장미 (Rose Blossom)
Butter
on the street (with J. Cole)
발걸음
Nxde
VIBE (feat. Jimin of BTS)
해요 (2022)
해금
That's Hilarious
너를 보는게 지친 하루에
Say I Love You
Monologue
Permission to Dance
STAY
Set Me Free Pt.2
Shut Down
새삥 (Prod. ZICO) (Feat. 호미들)
ELEVEN
나비무덤
KNOCK
취중고백
다시 사랑한다면
Pink Venom
그라데이션
TOMBOY
내가 아니라도
안녕이라고 말하지마
Cookie
FEARLESS
정이라고 하자 (Feat. 10CM)
그중에 그대를 만나
나의 마음에 (Seed)
Say My Name
다정히 내 이름을 부르면
그때 그 순간 그대로 (그그그)
오르트구름
빙글빙글 (Prod. R.Tee)
모든 날, 모든 순간 (Every day, Every Moment)
That’s Not How This Works (feat. Dan + Shay)
결국엔 너에게 닿아서

In [15]:
len(titles)

100

In [23]:
# artists를 뽑아보자

# 왜 103개가 뽑혔을까?
    # 듀엣곡 때문, 한 곡당 최소 2명의 아티스트
    # 즉 2개의 a tag가 존재
    # 아이태그인 a tag가 말썽이였음
        #부모 태그 소환
artists = soup.select('div.ellipsis.rank02')
len(artists)

100

In [25]:
artists[0].text
# 이 경우를 보니 아티스트가 중복되는 경우도 있었다.
    # 개발자 모드 f12를 켜서 보니, 그 밑에 또 다른 태그가 있었다.
    # 그러면 어떻게 해야할까?

'\nIVE (아이브)IVE (아이브)\n'

In [26]:
artists = soup.select('div.ellipsis.rank02 > span')
artists[0].text

# 크롤링은 결국 족보싸움이다.
    # 내가 원하는 태그 내 데이터에 id, Class가 불확실하다면,
        # 그 위의 부모태그, 혹은 조부모태그, 혹은 조상까지 타고 올라가야 할 수도 있다.

'IVE (아이브)'

### 수집한 타이틀, 아티스트 데이터를 for loop을 통해 리스트에 집어넣자

In [28]:
# 자료형을 확인해보자
type(titles)

# bs4.element.ResultSet
    # 리스트와 매우 유사하지만 엄연히 다른 객체
    # but 우리는 python 기반 pandas library를 사용해야한다.
    # 그러므로 반 리스트 2개를 선언해서 for loop으로 순차적으로 담자

bs4.element.ResultSet

In [31]:
# 빈 리스트를 선언

titles_list = []
artists_list = []

for i in range(len(titles)):
    titles_list.append(titles[i].text)
    artists_list.append(artists[i].text)
    
    print(titles[i].text, artists[i].text)

I AM IVE (아이브)
Kitsch IVE (아이브)
꽃 지수 (JISOO)
손오공 세븐틴 (SEVENTEEN)
파이팅 해야지 (Feat. 이영지) 부석순 (SEVENTEEN)
Ditto NewJeans
Hype boy NewJeans
사람 Pt.2 (feat. 아이유) Agust D
OMG NewJeans
사랑은 늘 도망가 임영웅
F*ck My Life 세븐틴 (SEVENTEEN)
Teddy Bear STAYC(스테이씨)
FRIEND THE END 볼빨간사춘기
사건의 지평선 윤하 (YOUNHA)
우리들의 블루스 임영웅
I Don't Think That I Like Her Charlie Puth
CHRISTIAN Zior Park
다시 만날 수 있을까 임영웅
London Boy 임영웅
After LIKE IVE (아이브)
Polaroid 임영웅
심(心) DK(디셈버)
이제 나만 믿어요 임영웅
Like Crazy 지민
먼지 세븐틴 (SEVENTEEN)
무지개 임영웅
빛이 나는 너에게 던 (DAWN)
아버지 임영웅
물론 허각
Love Me Like This NMIXX
Attention NewJeans
ANTIFRAGILE LE SSERAFIM (르세라핌)
A bientot 임영웅
LOVE DIVE IVE (아이브)
April shower 세븐틴 (SEVENTEEN)
인생찬가 임영웅
헤어지자 말해요 박재정
Cupid FIFTY FIFTY
사랑하지 않아서 그랬어 임한별
손이 참 곱던 그대 임영웅
Fire 세븐틴 (SEVENTEEN)
사랑해 진짜 임영웅
I Don't Understand But I Luv U 세븐틴 (SEVENTEEN)
NIGHT DANCER imase
연애편지 임영웅
Dangerously Charlie Puth
보금자리 임영웅
사랑인가 봐 멜로망스
Dynamite 방탄소년단
Heaven(2023) 임재현
사랑하기 싫어 지아
Zero NewJeans
밤이 무서워요 (Lonely Night) 주주 시크릿
Nostalgia 우디 (Woody)
봄날 방탄소년단
HOT 세븐틴 (SEVENTEEN)
너의 모든 순간 성시경
Perfume NCT 도재정
Candy NCT DREAM
가질 수 없는 너 #안녕
건물 사이에 피어난 장미 (Rose Blossom) H1-KEY (하이키)
Butter 방탄소년단
on the street (with J. Cole) j-hope, J. Cole
발걸음 DK(디셈버)
Nxde (여자)아이들
VIBE (feat. Jimin of BTS) 태양
해요 (2022) #안녕
해금 Agust D
That's Hilarious Charlie Puth
너를 보는게 지친 하루에 송하예
Say I Love You 우디 (Woody)
Monologue 테이
Permission to Dance 방탄소년단
STAY The Kid LAROI, Justin Bieber
Set Me Free Pt.2 지민
Shut Down BLACKPINK
새삥 (Prod. ZICO) (Feat. 호미들) 지코 (ZICO)
ELEVEN IVE (아이브)
나비무덤 포맨 (4MEN)
KNOCK 이채연
취중고백 김민석 (멜로망스)
다시 사랑한다면 한동근
Pink Venom BLACKPINK
그라데이션 10CM
TOMBOY (여자)아이들
내가 아니라도 주호
안녕이라고 말하지마 V.O.S
Cookie NewJeans
FEARLESS LE SSERAFIM (르세라핌)
정이라고 하자 (Feat. 10CM) BIG Naughty (서동현)
그중에 그대를 만나 김호중
나의 마음에 (Seed) 태양
Say My Name Say Yes!
다정히 내 이름을 부르면 경서예지, 전건호
그때 그 순간 그대로 (그그그) WSG워너비 (가야G)
오르트구름 윤하 (YOUNHA)
빙글빙글 (Prod. R.Tee) 헤이즈 (Heize)
모든 날, 모든 순간 (Every day, Every Moment) 폴킴
That’s Not How This Works (feat. Dan + Shay) Charlie Puth
결국엔 너에게 닿아서 WSG워너비 (가야G)

### DataFrame

In [32]:
# 1. Dictionary 형태로 만들어 줘야합니다.
    # Dictionary로 우선 선언해 줘야하는 이유:
    # 1. 각각의 행과 열에 대한 데이터를 쉽게 입력할 수 있다.
    # 2. frame 내 데이터 타입을 일치시키기 쉽게 구성 할 수 있다.
    
    # 3. dictionary로 먼저 저장을 해주면,
        # 데이터 구조가 보존이 됩니다.
        # Pandas Dataframe으로 변경할 때, 일관성이 유지가 됩니다.

In [34]:
melon_dic = {'title': titles_list,'artists' : artists_list}
melon_dic

{'title': ['I AM',
  'Kitsch',
  '꽃',
  '손오공',
  '파이팅 해야지 (Feat. 이영지)',
  'Ditto',
  'Hype boy',
  '사람 Pt.2 (feat. 아이유)',
  'OMG',
  '사랑은 늘 도망가',
  'F*ck My Life',
  'Teddy Bear',
  'FRIEND THE END',
  '사건의 지평선',
  '우리들의 블루스',
  "I Don't Think That I Like Her",
  'CHRISTIAN',
  '다시 만날 수 있을까',
  'London Boy',
  'After LIKE',
  'Polaroid',
  '심(心)',
  '이제 나만 믿어요',
  'Like Crazy',
  '먼지',
  '무지개',
  '빛이 나는 너에게',
  '아버지',
  '물론',
  'Love Me Like This',
  'Attention',
  'ANTIFRAGILE',
  'A bientot',
  'LOVE DIVE',
  'April shower',
  '인생찬가',
  '헤어지자 말해요',
  'Cupid',
  '사랑하지 않아서 그랬어',
  '손이 참 곱던 그대',
  'Fire',
  '사랑해 진짜',
  "I Don't Understand But I Luv U",
  'NIGHT DANCER',
  '연애편지',
  'Dangerously',
  '보금자리',
  '사랑인가 봐',
  'Dynamite',
  'Heaven(2023)',
  '사랑하기 싫어',
  'Zero',
  '밤이 무서워요 (Lonely Night)',
  'Nostalgia',
  '봄날',
  'HOT',
  '너의 모든 순간',
  'Perfume',
  'Candy',
  '가질 수 없는 너',
  '건물 사이에 피어난 장미 (Rose Blossom)',
  'Butter',
  'on the street (with J. Cole)',
  '발걸음',
  'Nxde',
  'VIBE (feat. Jimin of BTS)',
  '해요 (2022)',
  '해금',
  "That's Hilarious",
  '너를 보는게 지친 하루에',
  'Say I Love You',
  'Monologue',
  'Permission to Dance',
  'STAY',
  'Set Me Free Pt.2',
  'Shut Down',
  '새삥 (Prod. ZICO) (Feat. 호미들)',
  'ELEVEN',
  '나비무덤',
  'KNOCK',
  '취중고백',
  '다시 사랑한다면',
  'Pink Venom',
  '그라데이션',
  'TOMBOY',
  '내가 아니라도',
  '안녕이라고 말하지마',
  'Cookie',
  'FEARLESS',
  '정이라고 하자 (Feat. 10CM)',
  '그중에 그대를 만나',
  '나의 마음에 (Seed)',
  'Say My Name',
  '다정히 내 이름을 부르면',
  '그때 그 순간 그대로 (그그그)',
  '오르트구름',
  '빙글빙글 (Prod. R.Tee)',
  '모든 날, 모든 순간 (Every day, Every Moment)',
  'That’s Not How This Works (feat. Dan + Shay)',
  '결국엔 너에게 닿아서'],
 'artists': ['IVE (아이브)',
  'IVE (아이브)',
  '지수 (JISOO)',
  '세븐틴 (SEVENTEEN)',
  '부석순 (SEVENTEEN)',
  'NewJeans',
  'NewJeans',
  'Agust D',
  'NewJeans',
  '임영웅',
  '세븐틴 (SEVENTEEN)',
  'STAYC(스테이씨)',
  '볼빨간사춘기',
  '윤하 (YOUNHA)',
  '임영웅',
  'Charlie Puth',
  'Zior Park',
  '임영웅',
  '임영웅',
  'IVE (아이브)',
  '임영웅',
  'DK(디셈버)',
  '임영웅',
  '지민',
  '세븐틴 (SEVENTEEN)',
  '임영웅',
  '던 (DAWN)',
  '임영웅',
  '허각',
  'NMIXX',
  'NewJeans',
  'LE SSERAFIM (르세라핌)',
  '임영웅',
  'IVE (아이브)',
  '세븐틴 (SEVENTEEN)',
  '임영웅',
  '박재정',
  'FIFTY FIFTY',
  '임한별',
  '임영웅',
  '세븐틴 (SEVENTEEN)',
  '임영웅',
  '세븐틴 (SEVENTEEN)',
  'imase',
  '임영웅',
  'Charlie Puth',
  '임영웅',
  '멜로망스',
  '방탄소년단',
  '임재현',
  '지아',
  'NewJeans',
  '주주 시크릿',
  '우디 (Woody)',
  '방탄소년단',
  '세븐틴 (SEVENTEEN)',
  '성시경',
  'NCT 도재정',
  'NCT DREAM',
  '#안녕',
  'H1-KEY (하이키)',
  '방탄소년단',
  'j-hope, J. Cole',
  'DK(디셈버)',
  '(여자)아이들',
  '태양',
  '#안녕',
  'Agust D',
  'Charlie Puth',
  '송하예',
  '우디 (Woody)',
  '테이',
  '방탄소년단',
  'The Kid LAROI, Justin Bieber',
  '지민',
  'BLACKPINK',
  '지코 (ZICO)',
  'IVE (아이브)',
  '포맨 (4MEN)',
  '이채연',
  '김민석 (멜로망스)',
  '한동근',
  'BLACKPINK',
  '10CM',
  '(여자)아이들',
  '주호',
  'V.O.S',
  'NewJeans',
  'LE SSERAFIM (르세라핌)',
  'BIG Naughty (서동현)',
  '김호중',
  '태양',
  'Say Yes!',
  '경서예지, 전건호',
  'WSG워너비 (가야G)',
  '윤하 (YOUNHA)',
  '헤이즈 (Heize)',
  '폴킴',
  'Charlie Puth',
  'WSG워너비 (가야G)']}

In [41]:
# Dataframe
melon_df = pd.DataFrame(melon_dic)
melon_df

                                           title          artists
0                                           I AM        IVE (아이브)
1                                         Kitsch        IVE (아이브)
2                                              꽃       지수 (JISOO)
3                                            손오공  세븐틴 (SEVENTEEN)
4                            파이팅 해야지 (Feat. 이영지)  부석순 (SEVENTEEN)
..                                           ...              ...
95                                         오르트구름      윤하 (YOUNHA)
96                            빙글빙글 (Prod. R.Tee)      헤이즈 (Heize)
97         모든 날, 모든 순간 (Every day, Every Moment)               폴킴
98  That’s Not How This Works (feat. Dan + Shay)     Charlie Puth
99                                   결국엔 너에게 닿아서     WSG워너비 (가야G)

[100 rows x 2 columns]

In [43]:
# CSV파일로 내보내기
    #항상 파일로 내보내는 습관이 필요하다.
    # 나중에 다시 다 돌려서, 다시 뽑혀야하는 불상사가 빈번
    
melon_df.to_csv('C:/Users/user07/webcrawling/melon_chart.csv',encoding = 'euc-kr')

In [44]:
url = 'http://www.cgv.co.kr/movies/?lt=1&ft=0'
req.get(url)

In [45]:
res_cgv = req.get('http://www.cgv.co.kr/movies/?lt=1&ft=0', headers = head)
res_cgv

In [46]:
soup = bs(res_cgv.text,'lxml')
soup

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="ko" xml:lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="-1" http-equiv="Expires"/>
<meta content="no-cache" http-equiv="Pragma"/>
<meta content="No-Cache" http-equiv="Cache-Control"/>
<meta content="no" http-equiv="imagetoolbar"/>
<meta content="width=1024" name="viewport"/>
<meta content="CGV, 시지브이, 영화관, 극장, 영화, 티켓, 박스오피스, 극장, Movie, Theater, Cinema, Cgv, cgv, 예매, 상영작" name="keywords"/>
<meta content="CGV는 선진화된 관람문화와 최고의 서비스로 고객에게 잊을 수 없는 감동을 선사합니다. CGV홈페이지를 통해 영화 예매뿐만 아니라 그 이상의 서비스와 감동을 전달하고, 다양한 즐거움과 특별한 경험을 제공하고자 합니다." name="description"/>
<meta content="영화 그 이상의 감동. CGV" property="og:site_name"/>
<meta content="무비차트 &lt; 무비차트 | 영화 그 이상의 감동. CGV" id="ctl00_og_title" property="og:title"/>
<meta content="https://img.cgv.co.kr/WebApp/images/common/logo_new_kakao_prevw.png" id="ctl00_og_image" property="og:image"/>
<link href="http://m.cgv.co.kr" rel="alternate"/>
<link href="https://img.cgv.co.kr/theater_img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<title id="ctl00_headerTitle">무비차트 &lt; 무비차트 | 영화 그 이상의 감동. CGV</title>
<link href="https://img.cgv.co.kr/R2014/images/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="https://img.cgv.co.kr/R2014/css/webfont.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/css/reset.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/css/layout.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/css/module.css?20211209" media="all" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/css/content.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/css/common.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/css/eggupdate.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/css/print.css" media="print" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/js/jquery.ui/smoothness/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" type="text/css"/>
<script src="/common/js/extraTheaters.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/app.config.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.tmpl.min.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.validate.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.paging.min.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/jquery.ui/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/jquery.utils.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/app.utils.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/jquery.utils.pageing.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/app.init.js" type="text/javascript"></script>
<!--[if lte IE 9]><script type="text/javascript" src="https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.placeholder.js"></script><![endif]-->
<script src="https://img.cgv.co.kr/R2014/js/jquery.plugin/jquery.dotdotdot.min.js" type="text/javascript"></script>
<script src="https://img.cgv.co.kr/R2014/js/silverlight_link.js" type="text/javascript"></script>
<script charset="utf-8" src="https://img.cgv.co.kr/R2014/js/slick/slick.js" type="text/javascript"></script>
<link href="https://img.cgv.co.kr/R2014/css/phototicket/phototicket.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/css/slick.css" media="all" rel="stylesheet" type="text/css"/>
<link href="https://img.cgv.co.kr/R2014/css/slick-theme-custom.css" media="all" rel="stylesheet" type="text/css"/>
<script src="https://img.cgv.co.kr/R2014/js/icheck/login.timer.js" type="text/javascript"></script>
<script charset="utf-8" src="https://img.cgv.co.kr/R2014/js/icheck/icheck.min.js" type="text/javascript"></script>
<link href="https://img.cgv.co.kr/R2014/js/icheck/iCheck.css" rel="stylesheet" type="text/css"/>
<!-- 2020.05.07 감정지수/프리에그 프로젝트 추가 -->
<link href="https://img.cgv.co.kr/R2014/css/preegg.css" media="all" rel="stylesheet" type="text/css"/>
<!-- 홈페이지 CSS 일원화로 인한 반영 20220721 -->
<link href="https://img.cgv.co.kr/resource_pc/css/cgv.min.css" rel="stylesheet" type="text/css"/>
<script src="https://img.cgv.co.kr/resource_pc/js/cgvUi.js" type="text/javascript"></script>
<!-- 각페이지 Header Start-->
<!--/각페이지 Header End-->
<script type="text/javascript">
        //<![CDATA[
        _TRK_CP = "/영화/무비차트/무비차트";

        app.config('staticDomain', 'https://img.cgv.co.kr/R2014/')
            .config('imageDomain', 'https://img.cgv.co.kr')
            .config('isLogin', 'False');


        // AD FLOAT
        // 암호화 할 문자열과 키값(상수값)을 매개변수로 받는다.
        function EncryptAD(str, key) {
            output = new String;
            Temp = new Array();
            TextSize = str.length;
            for (i = 0; i < TextSize; i++) {
                // key 값을 원하는 대로 연산을 한다
                output += String.fromCharCode(str.charCodeAt(i) + parseInt(key) + 123 + i);
            }
            return output;
        }
        // 복호화
        // 암호화 된 문자열과 키값(상수값)을 매개변수로 받는다.
        function DecryptAD(str, key) {
            output = new String;
            Temp = new Array();
            TextSize = str.length;
            for (i = 0; i < TextSize; i++) {
                // 암호화시 사용한 연산과 같아야 한다.
                output += String.fromCharCode(str.charCodeAt(i) - (parseInt(key) + 123 + i));
            }

            return output;
        }

        function getCookieVal(offset) {
            var endstr = document.cookie.indexOf(";", offset);
            if (endstr == -1) endstr = document.cookie.length;
            return unescape(document.cookie.substring(offset, endstr));
        }
        function GetCookieAd(name) {
            var arg = name + "=";
            var alen = arg.length;
            var clen = document.cookie.length;
            var i = 0;
            while (i < clen) { //while open
                var j = i + alen;
                if (document.cookie.substring(i, j) == arg)
                    return getCookieVal(j);
                i = document.cookie.indexOf(" ", i) + 1;
                if (i == 0) break;
            } //while close
            return null;
        }
        function setCookieAD(name, value, expiredays) {
            var todayDate = new Date();
            todayDate.setTime(todayDate.getTime() + (expiredays * 24 * 60 * 60 * 1000));
            document.cookie = name + "=" + escape(value) + "; expires=" + todayDate.toGMTString() + "; path=/; domain=cgv.co.kr";
        }
        function CloseAD() {
            var AdUrl = window.location.href;
            var ArrAdUrl = AdUrl.split("/");

            var CurCookieName = 'CgvPopAd-' + ArrAdUrl[3];
            var CurCookieUrl = GetCookieAd(CurCookieName);
            var CookieUrl = ArrAdUrl[3];

            CookieUrl = EncryptAD(CookieUrl, "15442280");
            setCookieAD(CurCookieName, CookieUrl, '1');
            $(document).find('#ad_float1').hide();
        }
        function OpenAD() {
            var AdUrl = window.location.href;
            var ArrAdUrl = AdUrl.split("/");
            var CookieUrl = ArrAdUrl[3];
            var CurCookieName = 'CgvPopAd-' + ArrAdUrl[3];
            var CurCookieUrl = GetCookieAd(CurCookieName);

            if (CurCookieUrl == null) {
                CurCookieUrl = "";
            }
            else {
                CurCookieUrl = DecryptAD(CurCookieUrl, "15442280");
            }

            if (CurCookieUrl.indexOf(CookieUrl) != -1) {
                $(document).find('#ad_float1').hide();
            }

            //section.cgv.co.kr 매거진 체크
            var magazineckurl = GetCookieAd("CgvPopAd-magazine");
            if (magazineckurl != null) {
                var magazineck = DecryptAD(magazineckurl, "15442280");
                if (magazineck != null && magazineck == "magazine") {
                    //값이있는경우 표시하지않음
                    $(document).find('#ad_float1').hide();
                }
            }
        }



        //]]>
    </script>
</head>
<body class="">
<div class="skipnaiv">
<a href="#contents" id="skipHeader">메인 컨텐츠 바로가기</a>
</div>
<div id="cgvwrap">
<div class="cgv-ad-wrap" id="cgv_main_ad">
<div class="sect-head-ad" id="TopBarWrapper">
<div class="top_extend_ad_wrap">
<div class="adreduce" id="adReduce">
<iframe frameborder="0" height="80" id="TopBanner" leftmargin="0" marginheight="0" marginwidth="0" name="TopBanner" scrolling="no" src="//ad.cgv.co.kr/NetInsight/html/CGV/CGV_201401/sub@TopBar_EX" title="" topmargin="0" width="100%"></iframe>
</div>
<div class="adextend" id="adExtend"></div>
</div><!-- //.top_extend_ad_wrap -->
</div>
</div>
<!-- S Header
        Description
        - class 'nav' 에 class 'active' 추가시 서브메뉴노출
        - class 'nav' 에 class 'fixed' 추가시 상단고정되며 스타일 변경됨
     -->
<div class="header">
<!-- 서비스 메뉴 -->
<div class="header_content">
<div class="contents">
<h1 onclick=""><a href="/"><img alt="CGV" src="https://img.cgv.co.kr/R2014/images/common/logo/logoRed.png"/></a><span>CULTUREPLEX</span></h1>
<ul class="memberInfo_wrap">
<!-- Advertisement -->
<div class="ad-partner">
<a href="http://www.cgv.co.kr/culture-event/event/detailViewUnited.aspx?seq=31426&amp;menu=006">
<img alt="현대M포인트" onerror="this.onerror=null;javascript:;$('.ad-partner').hide();" src="https://img.cgv.co.kr/WingBanner/2023/0208/16758461047540.png"/>
</a>
</div>
<!-- /Advertisement -->
<li><a href="/user/login/?returnURL=http%3a%2f%2fwww.cgv.co.kr%2fmovies%2fdefault.aspx%3flt%3d1%26ft%3d0"><img alt="로그인" src="https://img.cgv.co.kr/R2014/images/common/ico/loginPassword.png"/><span>로그인</span></a></li>
<li><a href="/user/join/"><img alt="회원가입" src="https://img.cgv.co.kr/R2014/images/common/ico/loginJoin.png"/><span>회원가입</span></a></li>
<li><a href="/user/mycgv/"><img alt="MY CGV" src="https://img.cgv.co.kr/R2014/images/common/ico/loginMember.png"/><span>MY CGV</span></a></li>
<li><a href="/support/default.aspx"><img alt="고객센터" src="https://img.cgv.co.kr/R2014/images/common/ico/loginCustomer.png"/><span>고객센터</span></a></li>
</ul>
</div>
</div>
<script>
    //GA Analytics TopMenu 영역 LOG
    //빨강 CGV클릭
    $('.header_content > .contents > h1 > a').on({
        click: function (e) {
            gaEventLog('PC_GNB', '홈', '');
        }
    });
    //서비스 메뉴
    $('.header_content > .contents > ul > li > a').on({
        click: function (e) {
            gaEventLog('PC_GNB', '서비스메뉴_'+this.text, '');
        }
    });



</script>
<!-- 서비스 메뉴 -->
<!-- 서브 메뉴 -->
<script type="text/javascript">
    $(document).ready(function () {
        $('.nav_menu > li > h2 > a').on({
            mouseenter: function (e) {
                var target = e.target;
                $(target).parents('.nav_menu').find('.nav_overMenu').slideDown(function () {
                    $('.nav').addClass('active');
                });
            },
            click: function (e) {
                var target = e.target;
                if (!$('.nav').hasClass('active')) {
                    $(this).trigger('mouseenter');
                } else {
                    $('.nav').trigger('mouseleave');
                }
            }
        });

        /********************************************************
        //서브메뉴 구글 GA Analytics 로그 처리 - 2022.01.12 myilsan
        ********************************************************/
        //cgv화이트 메뉴클릭
        $('.nav > .contents > h1 > a').on({
             click: function (e) {
                 gaEventLog('PC_GNB', '홈', '');
            }
        });

        //주메뉴 클릭
        $('.nav_menu > li > h2 > a').on({
            click: function (e) {
                gaEventLog('PC_GNB', '주메뉴_' + this.text, '');
            }
        });

        //주메뉴 하위메뉴 클릭
        $('.nav_overMenu > dd > h3 > a').on({
            click: function (e) {
                var target = e.target;
                var parText = $(target).parents('.nav_overMenu').find('dt')[0].innerText;
                gaEventLog('PC_GNB', parText + '_' + this.text, '');
            }
        });

        //하위메뉴 최상위 클릭
        $(".nav_overMenu > dt > h2 > a").on({
            click: function (e) {
                gaEventLog('PC_GNB',this.text + '_' + this.text, '');
            }
        });

        //------------------end----------------------- [@,.o]>

        $('.nav').on({
            mouseleave: function (e) {
                $(this).find('.nav_overMenu').slideUp(200, function () {
                    $('.nav').removeClass('active');
                });
            }
        });

        $('.totalSearch_wrap input[type=text]').on({
            focusin: function () {
                $('.totalSearch_wrap').addClass("active");
            }
        });

        $('.btn_totalSearchAutocomplete_close').on({
            click: function () {
                $('.totalSearch_wrap').removeClass("active");
            },
            focusout: function (e) {
                //     $('.totalSearch_wrap').removeClass("active");

            }
        });

        $(this).on({
            scroll: function (e) {
                /* S GNB fixed */
                var headerOffsetT = $('.header').offset().top;
                var headerOuterH = $('.header').outerHeight(true);
                var fixedHeaderPosY = headerOffsetT + headerOuterH;
                var scrollT = $(this).scrollTop();
                var scrollL = $(this).scrollLeft();

                if (scrollT >= fixedHeaderPosY) {
                    $('.nav').addClass('fixed');
                    $('.fixedBtn_wrap').addClass('topBtn');
                } else {
                    $('.nav').removeClass('fixed');
                    $('.fixedBtn_wrap').removeClass('topBtn');
                }

                /* S > GNB fixed 좌우 스크롤
                Description
                - GNB가 fixed 되었을때 좌우 스크롤 되게 처리
                */
                if ($('.nav').hasClass('fixed')) {
                    $('.nav').css({ 'left': -1 * scrollL })
                } else {
                    $('.nav').css({ 'left': 0 })
                }
                /* E > GNB fixed 좌우 스크롤 */
                /* S GNB fixed */
            }
        });

        $('.btn_gotoTop').on({
            click: function () {
                $('html, body').stop().animate({
                    scrollTop: '0'
                }, 400);
            }
        });

        //통합검색 상단 검색 버튼
        $('#btn_header_search').on('click', function () {


            if ($('#header_ad_keyword').val() != "")
                goSearch($('#header_ad_keyword'));      //광고
            else
                goSearch($('#header_keyword'));


            return false;
        });

        //통합검색 검색어 입력창
        $('#header_keyword').keyup(function (e) {
            if (e.keyCode == 13) goSearch($('#header_keyword'));
        });

         //검색 입력창 클릭 시 광고값 reset
        $('#header_keyword').on('click', function () {
            $(this).attr('placeholder', '');
            $('#header_ad_keyword').val('');
        });

    });

    //통합검색
    function goSearch($objKeyword) {

        if ($objKeyword.val() == "") {
            alert("검색어를 입력해 주세요");
            $objKeyword.focus();
            return false;
        }

        //GA 검색로그
        gaEventLog('PC_GNB', '검색', $objKeyword.val());
        location = "/search/?query=" + escape($objKeyword.val());
    }



    //상단 키워드 광고 (S)
    function AdSearchExt(txt, SearchText) {
        $('#header_keyword').attr('placeholder', txt);
        $('#header_ad_keyword').val(SearchText);
    }

    function hdIcoSet(left, sh) { }
    //상단 키워드 광고 (E)

    //상단광고닫기
    function hideCgvTopAd() {
        $(".cgv-ad-wrap").hide();
        $('#wrap_main_notice').parent('div').css('top', 280);
    }

    //비즈스프링 클릭로그
    function setClickLog(title) {
        // eval("try{trk_clickTrace('EVT', '" + title + "')}catch(_e){}");
    }

</script>
<div class="nav">
<div class="contents">
<h1><a href="/" tabindex="-1"><img alt="CGV" src="https://img.cgv.co.kr/R2014/images/common/logo/logoWhite.png"/></a></h1>
<ul class="nav_menu">
<li>
<h2><a href="/movies/?lt=1&amp;ft=0">영화</a></h2>
<dl class="nav_overMenu">
<dt><h2><a href="/movies/?lt=1&amp;ft=0" tabindex="-1">영화</a></h2></dt>
<dd><h3><a href="/movies/?lt=1&amp;ft=0">무비차트</a></h3></dd>
<dd><h3><a href="/arthouse/">아트하우스</a></h3></dd>
<dd><h3><a href="/culture-event/event/detailViewUnited.aspx?seq=30717">ICECON</a></h3></dd>
</dl>
</li>
<li>
<h2><a href="/theaters/">극장</a></h2>
<dl class="nav_overMenu">
<dt><h2><a href="/theaters/" tabindex="-1">극장</a></h2></dt>
<dd><h3><a href="/theaters/">CGV 극장</a></h3></dd>
<dd><h3><a href="/theaters/special/defaultNew.aspx">특별관</a></h3></dd>
</dl>
</li>
<li>
<h2><a href="/ticket/"><strong>예매</strong></a></h2>
<dl class="nav_overMenu">
<dt><h2><a href="/ticket/" tabindex="-1">예매</a></h2></dt>
<dd><h3><a href="/ticket/">빠른예매</a></h3></dd>
<dd><h3><a href="/reserve/show-times/">상영스케줄</a></h3></dd>
<dd><h3><a href="/ticket/eng/newdefault.aspx">English Ticketing</a></h3></dd>
<dd><h3><a href="/reserve/show-times/eng/">English Schedule</a></h3></dd>
</dl>
</li>
<li>
<h2><a href="/culture-event/popcorn-store/">스토어</a></h2>
<dl class="nav_overMenu">
<dt><h2><a href="/culture-event/popcorn-store/" tabindex="-1">스토어</a></h2></dt>
<dd><h3><a href="/culture-event/popcorn-store/store-category.aspx?CategoryIdx=1">패키지</a></h3></dd>
<dd><h3><a href="/culture-event/popcorn-store/store-category.aspx?CategoryIdx=2">영화관람권</a></h3></dd>
<dd><h3><a href="/culture-event/popcorn-store/store-category.aspx?CategoryIdx=3">기프트카드</a></h3></dd>
<dd><h3><a href="/culture-event/popcorn-store/store-category.aspx?CategoryIdx=4">콤보</a></h3></dd>
<dd><h3><a href="/culture-event/popcorn-store/store-category.aspx?CategoryIdx=5">팝콘</a></h3></dd>
<dd><h3><a href="/culture-event/popcorn-store/store-category.aspx?CategoryIdx=6">음료</a></h3></dd>
<dd><h3><a href="/culture-event/popcorn-store/store-category.aspx?CategoryIdx=7">스낵</a></h3></dd>
<dd><h3><a href="/culture-event/popcorn-store/store-category.aspx?CategoryIdx=10">플레이존</a></h3></dd>
<dd><h3><a class="arrowR" href="https://brand.naver.com/cgv" target="_blank">씨네샵</a></h3></dd>
</dl>
</li>
<li>
<h2 onclick="gaEventLog('PC_GNB','주메뉴_이벤트','')"><a href="/culture-event/event/defaultNew.aspx">이벤트</a></h2>
<dl class="nav_overMenu">
<dt><h2><a href="/culture-event/event/defaultNew.aspx?mCode=001" tabindex="-1">이벤트</a></h2></dt>
<dd><h3><a href="/culture-event/event/defaultNew.aspx?mCode=001">SPECIAL</a></h3></dd>
<dd><h3><a href="/culture-event/event/defaultNew.aspx?mCode=004">영화/예매</a></h3></dd>
<dd><h3><a href="/culture-event/event/defaultNew.aspx?mCode=008">멤버십/CLUB</a></h3></dd>
<dd><h3><a href="/culture-event/event/defaultNew.aspx?mCode=005">CGV 극장별</a></h3></dd>
<dd><h3><a href="/culture-event/event/defaultNew.aspx?mCode=006">제휴할인</a></h3></dd>
<dd><h3><a href="/user/mycgv/event/result_list.aspx">당첨자 발표</a></h3></dd>
<dd><h3><a href="/culture-event/event/end-list.aspx">종료된 이벤트</a></h3></dd>
</dl>
</li>
<li>
<h2 onclick="gaEventLog('PC_GNB','주메뉴_해택','')"><a href="/discount/discountlist.aspx">혜택</a></h2>
<dl class="nav_overMenu">
<dt><h2><a href="/discount/discountlist.aspx" tabindex="-1">혜택</a></h2></dt>
<dd><h3><a href="/discount/discountlist.aspx">CGV 할인정보</a></h3></dd>

In [63]:
ranking = soup.select('div.box-contents > a > strong')
ranking[0].text

'가디언즈 오브 갤럭시-Volume 3'

In [64]:
for i in range(len(ranking)):
    print(ranking[i].text)

가디언즈 오브 갤럭시-Volume 3
슈퍼 마리오 브라더스
드림
존 윅 4
극장판 짱구는 못말려-동물소환 닌자 배꼽수비대
스즈메의 문단속
더 퍼스트 슬램덩크
옥수역귀신
LE SSERAFIM COMEBACK SHOW - UNFORGIVEN in CGV
2001 스페이스 오디세이
뮤지컬 공연실황, 알쏭달쏭 캐치! 티니핑 <신비한 상자를 열어라!>
리바운드
클로즈
블레이드 러너-더 파이널 컷
무명
항구의 니쿠코짱!
킬링 로맨스
아임 히어로 더 파이널
롱디

In [68]:
type(ranking)

bs4.element.ResultSet

In [72]:
ranking_list = []

for i in range(len(ranking)):
    ranking_list.append(ranking[i].text)
    
    print(ranking[i].text)

가디언즈 오브 갤럭시-Volume 3
슈퍼 마리오 브라더스
드림
존 윅 4
극장판 짱구는 못말려-동물소환 닌자 배꼽수비대
스즈메의 문단속
더 퍼스트 슬램덩크
옥수역귀신
LE SSERAFIM COMEBACK SHOW - UNFORGIVEN in CGV
2001 스페이스 오디세이
뮤지컬 공연실황, 알쏭달쏭 캐치! 티니핑 <신비한 상자를 열어라!>
리바운드
클로즈
블레이드 러너-더 파이널 컷
무명
항구의 니쿠코짱!
킬링 로맨스
아임 히어로 더 파이널
롱디

In [73]:
ranking_dic = {'순위': ranking_list}
ranking_dic

{'순위': ['가디언즈 오브 갤럭시-Volume 3',
  '슈퍼 마리오 브라더스',
  '드림',
  '존 윅 4',
  '극장판 짱구는 못말려-동물소환 닌자 배꼽수비대',
  '스즈메의 문단속',
  '더 퍼스트 슬램덩크',
  '옥수역귀신',
  'LE SSERAFIM COMEBACK SHOW - UNFORGIVEN in CGV',
  '2001 스페이스 오디세이',
  '뮤지컬 공연실황, 알쏭달쏭 캐치! 티니핑 <신비한 상자를 열어라!>',
  '리바운드',
  '클로즈',
  '블레이드 러너-더 파이널 컷',
  '무명',
  '항구의 니쿠코짱!',
  '킬링 로맨스',
  '아임 히어로 더 파이널',
  '롱디']}

In [74]:
ranking_df = pd.DataFrame(ranking_dic)
ranking_df

                                               순위
0                            가디언즈 오브 갤럭시-Volume 3
1                                     슈퍼 마리오 브라더스
2                                              드림
3                                           존 윅 4
4                       극장판 짱구는 못말려-동물소환 닌자 배꼽수비대
5                                        스즈메의 문단속
6                                      더 퍼스트 슬램덩크
7                                           옥수역귀신
8   LE SSERAFIM COMEBACK SHOW - UNFORGIVEN in CGV
9                                  2001 스페이스 오디세이
10          뮤지컬 공연실황, 알쏭달쏭 캐치! 티니핑 <신비한 상자를 열어라!>
11                                           리바운드
12                                            클로즈
13                                블레이드 러너-더 파이널 컷
14                                             무명
15                                      항구의 니쿠코짱!
16                                         킬링 로맨스
17                                   아임 히어로 더 파이널
18                                             롱디

In [75]:
ranking_df.to_csv('C:/Users/user07/webcrawling/cgv_ranking.csv',encoding = 'euc-kr')